# Generated by Django 4.0.4 on 2022-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_full_url', models.CharField(max_length=300)),
                ('url', models.CharField(blank=None, default=None, editable=False, max_length=30, unique=True)),
                ('redirects', models.IntegerField(default=0)),
            ],
        ),
    ]
