# Generated by Django 4.0.4 on 2022-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_rename_mapped_full_url_url_full_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirects',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
