# Generated by Django 4.0.4 on 2022-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=None, default='N/A', editable=False, max_length=15, unique=True),
        ),
    ]
